version: '2'
services:
  db:
    image: postgres
  redis:
    image: redis
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "bundle install && yarn install && bundle exec rake foreman:dev --trace"
    environment:
      - OVERRIDE_DB_HOST=db
      - OVERRIDE_DB_PASSWORD=
      - REDIS_URL=redis://redis:6379
    working_dir: /dtv
    volumes:
      - .:/dtv
    ports:
      - "3808:3808"
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true
