branch-defaults:
  master:
    environment: drivevote-dev
  production:
    environment: drivevote-prod
  worker_tier:
    environment: drivevote-worker
deploy:
  artifact: tmp/deploy_artifact.zip
global:
  application_name: drive.vote
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-2
  profile: null
  sc: git
